const express = require('express')
const UserController = require('./controllers/UserController')
const VehicleController = require('./controllers/VehicleController')
const LoginAuth = require('./middlewares/LoginAuth')

const router = express.Router()

router.get('/users', UserController.findAll)
router.get('/users/address', UserController.findAllWithAddress)
router.get('/user/:id', UserController.findById)
router.get('/users/rating', UserController.findAllOrderByRating)
router.get('/user/:id/vehicles', UserController.findByIdWithVehicles)
router.get('/user/:id/favorites', LoginAuth, UserController.findFavorites)
router.patch('/user/:id/rating', UserController.updateRating)
router.put('/user/:id', LoginAuth, UserController.update)
router.delete('/user/:id', LoginAuth, UserController.delete)
router.post('/user', UserController.create)
router.post('/user/:id/address', LoginAuth, UserController.createAddress)
router.post('/user/login', UserController.login)
router.post('/user/recoverPassword', UserController.recoverPassword)
router.post('/user/changePassword', UserController.changePassword)
router.post('/user/:id/emailToVerify', LoginAuth, UserController.sendEmailToVerify)
router.post('/user/:id/verifyEmail', LoginAuth, UserController.verifyEmail)
router.post('/user/:id/setOrUnsetFavorite', LoginAuth, UserController.setOrUnsetFavorite)

router.post('/vehicle', LoginAuth, VehicleController.create)
router.get('/vehicles', VehicleController.findAll)
router.get('/vehicle/:id', VehicleController.findById)
router.put('/vehicle/:id', LoginAuth, VehicleController.update)
router.delete('/vehicle/:id', LoginAuth, VehicleController.delete)
router.get('/vehicles/cars', VehicleController.findAllCars)
router.get('/vehicles/motorcycles', VehicleController.findAllMotorcycles)
router.get('/vehicles/categories', VehicleController.findWithCategories)

module.exports = router
